icon:
  symbol: ICX
  network_info:
    mainnet:
      network_api: https://ctz.solidwallet.io
      nid: '0x1'
    lisbon:
      network_api: https://lisbon.net.solidwallet.io
      nid: '0x2'
    techteam:
      network_api: https://techteam.net.solidwallet.io
      nid: '0xa'
    cdnet:
      network_api: http://20.20.1.122:9000
      nid: '0x53'
    iiss:
      network_api: http://iiss-test-endpoint:9000
      nid: '0x53'
    icontest:
      network_api: http://100.91.150.17:9000
      nid: '0x53'
havah:
  symbol: HVH
  network_info:
    mainnet:
      planet_api: https://planet.havah.io
      network_api: https://ctz.havah.io
      nid: '0x100'
    vega:
      planet_api: https://planet.vega.havah.io
      network_api: https://ctz.vega.havah.io
      nid: '0x101'
    deneb:
      planet_api: https://planet.dev.havah.io
      network_api: https://ctz.dev.havah.io
      nid: '0x110'
    svm_havah:
      network_api: http://20.20.1.153:9900
      nid: '0x8361'
